# Generated by Django 3.1.5 on 2021-01-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studlearn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beginnercourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlecourse', models.CharField(max_length=100)),
                ('subtitlecourse', models.CharField(max_length=100)),
                ('imgcourse', models.ImageField(upload_to='pics')),
                ('viewscourse', models.CharField(max_length=300)),
                ('datecourse', models.DateField(blank=True)),
                ('desccourse', models.TextField()),
                ('offercourse', models.CharField(max_length=100)),
                ('pricecourse', models.IntegerField(max_length=100)),
                ('courseauthor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Coursedetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseimg', models.ImageField(upload_to='pics')),
                ('coursename', models.CharField(max_length=100)),
                ('coursecontent', models.CharField(max_length=200)),
                ('studententrollcount', models.CharField(max_length=100)),
                ('uploaddate', models.DateField(blank=True)),
                ('desccourse', models.TextField()),
            ],
        ),
    ]
