# Generated by Django 3.1.5 on 2021-01-12 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studlearn', '0002_beginnercourses_coursedetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beginnercourses',
            name='pricecourse',
            field=models.IntegerField(),
        ),
    ]
