# Generated by Django 3.1.5 on 2021-01-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studlearn', '0003_auto_20210112_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='beginnercourses',
            name='courseduration',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
