# Generated by Django 3.1.5 on 2021-01-12 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studlearn', '0004_beginnercourses_courseduration'),
    ]

    operations = [
        migrations.AddField(
            model_name='beginnercourses',
            name='coursemode',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='beginnercourses',
            name='offercourse',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
