# Generated by Django 3.1.5 on 2021-01-12 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studlearn', '0005_auto_20210112_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intermediatecourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlecourse', models.CharField(max_length=100)),
                ('subtitlecourse', models.CharField(max_length=100)),
                ('imgcourse', models.ImageField(upload_to='pics')),
                ('viewscourse', models.CharField(max_length=300)),
                ('datecourse', models.DateField(blank=True)),
                ('desccourse', models.TextField()),
                ('offercourse', models.CharField(blank=True, max_length=100)),
                ('pricecourse', models.IntegerField()),
                ('courseauthor', models.CharField(max_length=100)),
                ('courseduration', models.CharField(max_length=100)),
                ('coursemode', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mastercourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlecourse', models.CharField(max_length=100)),
                ('subtitlecourse', models.CharField(max_length=100)),
                ('imgcourse', models.ImageField(upload_to='pics')),
                ('viewscourse', models.CharField(max_length=300)),
                ('datecourse', models.DateField(blank=True)),
                ('desccourse', models.TextField()),
                ('offercourse', models.CharField(blank=True, max_length=100)),
                ('pricecourse', models.IntegerField()),
                ('courseauthor', models.CharField(max_length=100)),
                ('courseduration', models.CharField(max_length=100)),
                ('coursemode', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Professioncourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlecourse', models.CharField(max_length=100)),
                ('subtitlecourse', models.CharField(max_length=100)),
                ('imgcourse', models.ImageField(upload_to='pics')),
                ('viewscourse', models.CharField(max_length=300)),
                ('datecourse', models.DateField(blank=True)),
                ('desccourse', models.TextField()),
                ('offercourse', models.CharField(blank=True, max_length=100)),
                ('pricecourse', models.IntegerField()),
                ('courseauthor', models.CharField(max_length=100)),
                ('courseduration', models.CharField(max_length=100)),
                ('coursemode', models.CharField(max_length=100)),
            ],
        ),
    ]
