# Generated by Django 3.1.5 on 2021-01-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studlearn', '0006_intermediatecourses_mastercourses_professioncourses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doubtqueryask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studname', models.CharField(max_length=100)),
                ('studemail', models.EmailField(max_length=254)),
                ('studmobile', models.CharField(max_length=100)),
                ('langdoubt', models.CharField(max_length=100)),
            ],
        ),
    ]
