# Generated by Django 3.1.5 on 2021-01-13 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studlearn', '0007_doubtqueryask'),
    ]

    operations = [
        migrations.AddField(
            model_name='beginnercourses',
            name='daycourse',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
